import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, addDoc, doc, setDoc, getDoc, getDocs, updateDoc, deleteDoc, query, where, orderBy, limit, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBbRoIhI0iAaDdgKbA6LsA-YXfFtXcuJPc",authDomain:"bagdadbreadfactorybd.firebaseapp.com",projectId:"bagdadbreadfactorybd",storageBucket:"bagdadbreadfactorybd.firebasestorage.app",messagingSenderId:"13667225455",appId:"1:13667225455:web:d769af316cd8e28adc229a",measurementId:"G-R75HG7EM61"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),googleProvider=new GoogleAuthProvider();
const money=n=>`৳${Number(n||0).toLocaleString("en-BD",{maximumFractionDigits:2})}`;
const ORDER_STEPS=["pending","confirmed","preparing","ready_for_pickup","out_for_delivery","delivered","cancelled"];
const ROLE_LABELS={admin:"Super Admin",manager:"Manager",branch_manager:"Branch Manager",factory_staff:"Factory Staff",staff:"Staff",attendance_staff:"Attendance Staff",delivery:"Delivery",customer:"Customer"};
const PERMISSIONS={
 admin:new Set(["inventory","purchases","cost","branches","deliveries","staff","reports","users","activity"]),
 manager:new Set(["inventory","purchases","cost","branches","deliveries","staff","reports","activity"]),
 branch_manager:new Set(["inventory","purchases","cost","branches","deliveries","staff","reports","activity"]),
 factory_staff:new Set(["inventory","purchases","cost","deliveries"]),
 staff:new Set(["inventory","deliveries","orders"]),
 attendance_staff:new Set(["staff"]),
 delivery:new Set(["deliveries"]),
 customer:new Set([])
};
let currentUser=null,currentRole=null,currentProfile=null,branchId=null;
let ordersCache=[],inventoryCache=[],purchasesCache=[],suppliersCache=[],branchesCache=[],deliveriesCache=[],employeesCache=[],attendanceCache=[],recipesCache=[],reportsOrdersCache=[],expensesCache=[];
const $=id=>document.getElementById(id), money0=n=>money(Number(n)||0);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function hasPerm(p){return currentRole==="admin"||PERMISSIONS[currentRole]?.has(p)||false}
function canEdit(p){return currentRole==="admin"||currentRole==="manager"||(currentRole==="branch_manager"&&!['branches','users','activity'].includes(p))||(p==="inventory"&&currentRole==="factory_staff")||(p==="deliveries"&&currentRole==="delivery")||(p==="attendance"&&(currentRole==="attendance_staff"||currentRole==="staff"))}
function fmtDate(v){const d=v?.toDate?v.toDate():(v?new Date(v):null);return d&&!isNaN(d)?d.toLocaleString("en-BD",{dateStyle:"medium",timeStyle:"short"}):"—"}
function dateKey(v){const d=v?.toDate?v.toDate():new Date(v);return isNaN(d)?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600)}
function showOnly(el){[$("loginScreen"),$("deniedScreen"),$("appShell")].forEach(s=>{if(s)s.classList.toggle("hidden",s!==el)})}
async function logActivity(action,collectionName,recordId,details=""){
  if(!currentUser)return;
  try{await addDoc(collection(db,"activityLogs"),{action,collection:collectionName,recordId:String(recordId||""),details,userId:currentUser.uid,userName:currentProfile?.name||currentUser.email||"Unknown",role:currentRole,createdAt:serverTimestamp(),branchId:currentProfile?.branchId||null});}catch(e){console.warn("Activity log failed",e)}
}

// AUTH
$("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(err){console.error(err);$("loginError").textContent="Sign-in failed. Check your email and password."}});
$("googleLoginBtn")?.addEventListener("click",async()=>{try{await signInWithPopup(auth,googleProvider)}catch(err){console.error(err);$("loginError").textContent="Google sign-in failed."}});
$("deniedSignOut")?.addEventListener("click",()=>signOut(auth));$("sidebarSignOut")?.addEventListener("click",()=>signOut(auth));
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){currentRole=null;showOnly($("loginScreen"));return}try{const s=await getDoc(doc(db,"users",user.uid));currentProfile=s.exists()?s.data():{};currentRole=currentProfile.role||null;branchId=currentProfile.branchId||null}catch(e){console.error(e);currentProfile={};currentRole=null}if(!PERMISSIONS[currentRole]||currentRole==="customer"){showOnly($("deniedScreen"));return}$("sidebarName").textContent=currentProfile.name||user.email||"Staff";$("sidebarRole").textContent=ROLE_LABELS[currentRole]||currentRole;applyPermissions();showOnly($("appShell"));await loadAllCore();navigate("panel-dashboard")});
function applyPermissions(){document.querySelectorAll("[data-perm]").forEach(el=>{const p=el.dataset.perm;el.style.display=hasPerm(p)?"":"none"});document.querySelectorAll(".admin-nav button[data-perm]").forEach(el=>el.style.display=hasPerm(el.dataset.perm)?"":"none");document.querySelectorAll("[data-manager-only]").forEach(el=>el.style.display=(currentRole==="admin"||currentRole==="manager")?"":"none")}

// NAVIGATION
function navigate(target){document.querySelectorAll(".admin-nav button[data-target]").forEach(b=>b.classList.toggle("active",b.dataset.target===target));document.querySelectorAll(".admin-panel").forEach(p=>p.classList.toggle("active",p.id===target));const map={"panel-dashboard":loadDashboard,"panel-inventory":loadInventory,"panel-purchases":loadPurchases,"panel-cost":loadCostPanel,"panel-branches":loadBranches,"panel-deliveries":loadDeliveries,"panel-staff":loadStaff,"panel-orders":loadOrders,"panel-reports":generateReport,"panel-notifications":loadNotifications,"panel-users":loadUsers,"panel-activity":loadActivity};if(map[target])map[target]();}
document.querySelectorAll(".admin-nav button[data-target]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.target)));

async function loadAllCore(){await Promise.allSettled([loadBranches(),loadInventory(),loadPurchases(),loadSuppliers(),loadEmployees(),loadAttendance(),loadDeliveries(),loadExpenses(),loadOrders(),loadRecipes()]);await loadDashboard()}
async function safeGet(name,opts={}){let q=collection(db,name);const branchScopedCollections=new Set(["inventory","purchases","stockTransfers","shipments","expenses","employees","attendance","orders"]);if(currentRole==="branch_manager"&&branchId&&branchScopedCollections.has(name)){q=query(q,where("branchId","==",branchId));}else if(opts.order){q=query(q,orderBy(opts.order,"desc"),limit(opts.limit||300));}else q=query(q,limit(opts.limit||300));const s=await getDocs(q);const out=s.docs.map(d=>({id:d.id,...d.data()}));if(opts.order)out.sort((a,b)=>{const av=a[opts.order]?.toDate?a[opts.order].toDate():new Date(a[opts.order]||0),bv=b[opts.order]?.toDate?b[opts.order].toDate():new Date(b[opts.order]||0);return bv-av});return out}

// DASHBOARD
async function loadDashboard(){try{if(!ordersCache.length)ordersCache=await safeGet("orders",{order:"createdAt",limit:500});if(!inventoryCache.length)inventoryCache=await safeGet("inventory",{limit:500});if(!deliveriesCache.length)deliveriesCache=await safeGet("shipments",{order:"createdAt",limit:300});if(!attendanceCache.length)attendanceCache=await safeGet("attendance",{order:"date",limit:300});if(!expensesCache.length)expensesCache=await safeGet("expenses",{order:"createdAt",limit:500});}catch(e){console.error("Dashboard",e)}const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),month=new Date(now.getFullYear(),now.getMonth(),1);const valid=ordersCache.filter(o=>o.orderStatus!=="cancelled");const dayOrders=valid.filter(o=>{const d=o.createdAt?.toDate?o.createdAt.toDate():new Date(o.createdAt);return !isNaN(d)&&d>=today});const monthOrders=valid.filter(o=>{const d=o.createdAt?.toDate?o.createdAt.toDate():new Date(o.createdAt);return !isNaN(d)&&d>=month});const salesToday=dayOrders.reduce((a,o)=>a+Number(o.total||0),0),monthlyRevenue=monthOrders.reduce((a,o)=>a+Number(o.total||0),0),monthlyExpenses=expensesCache.filter(e=>{const d=e.createdAt?.toDate?e.createdAt.toDate():new Date(e.createdAt);return !isNaN(d)&&d>=month}).reduce((a,e)=>a+Number(e.amount||0),0);const low=inventoryCache.filter(i=>Number(i.quantity??i.stock??0)<=Number(i.minimumStock??i.minStock??0));const pending=deliveriesCache.filter(d=>["pending","dispatched"].includes(d.status||"pending"));const att=attendanceCache.filter(a=>dateKey(a.date||a.createdAt)===dateKey(today));const present=att.filter(a=>a.status==="present").length;$("statSalesToday").textContent=money(salesToday);$("statOrdersToday").textContent=dayOrders.length;$("statMonthlyRevenue").textContent=money(monthlyRevenue);$("statMonthlyExpenses").textContent=money(monthlyExpenses);$("statProfit").textContent=money(monthlyRevenue-monthlyExpenses);$("statProfit").className=monthlyRevenue-monthlyExpenses<0?"kpi-negative":"kpi-positive";$("statLowStock").textContent=low.length;$("statLowStock").className=low.length?"warn-text":"";$("statPendingDeliveries").textContent=pending.length;$("statAttendance").textContent=present;$("statAttendanceSub").textContent=`${present} present / ${att.length} records`;renderRecentOrders();renderAlerts();}
$("refreshDashboard")?.addEventListener("click",async()=>{ordersCache=[];inventoryCache=[];deliveriesCache=[];attendanceCache=[];expensesCache=[];await loadDashboard();toast("Dashboard refreshed")});
function renderRecentOrders(){const body=$("recentOrdersBody");body.innerHTML=ordersCache.slice(0,8).map(orderRow).join("")||`<tr><td colspan="6" class="empty-cell">No orders yet.</td></tr>`;bindOrderControls(body)}
function alertData(){const low=inventoryCache.filter(i=>Number(i.quantity??i.stock??0)<=Number(i.minimumStock??i.minStock??0));const pending=deliveriesCache.filter(d=>["pending","dispatched"].includes(d.status||"pending"));const pendingOrders=ordersCache.filter(o=>(o.orderStatus||"pending")==="pending");const price=purchasesCache.map(p=>p).filter(p=>Number(p.previousUnitCost)>0&&Number(p.unitCost)>Number(p.previousUnitCost)*1.1);const today=dateKey(new Date());const absent=employeesCache.length-attendanceCache.filter(a=>dateKey(a.date||a.createdAt)===today&&a.status==="present").length;return [...low.map(i=>({icon:"⚠️",title:`${i.name||i.itemName} stock low`,text:`${i.quantity??i.stock??0} ${i.unit||"units"} left; minimum ${i.minimumStock??i.minStock??0}`})),...price.map(p=>({icon:"📈",title:`${p.itemName||p.name} price increased`,text:`${money(p.previousUnitCost)} → ${money(p.unitCost)}`})),...pending.map(d=>({icon:"🚚",title:"Delivery pending",text:`${d.branchName||d.branchId||"Branch"} — ${d.status||"pending"}`})),...pendingOrders.map(o=>({icon:"🛒",title:"Payment/order pending",text:`Order ${o.id.slice(0,8)} — ${money(o.total)}`})),...(absent>0&&employeesCache.length?[{icon:"👤",title:"Attendance check",text:`${Math.max(0,absent)} staff do not have a present record today.`}]:[])];}
function renderAlerts(){const data=alertData().slice(0,12);const html=data.map(a=>`<div class="alert-item"><div class="alert-icon">${a.icon}</div><div><b>${esc(a.title)}</b><small>${esc(a.text)}</small></div></div>`).join("")||`<div class="empty-cell">✓ No active alerts.</div>`;$("dashboardAlerts").innerHTML=html;$("notificationsList").innerHTML=html}

// INVENTORY
async function loadInventory(){try{inventoryCache=await safeGet("inventory",{limit:500})}catch(e){console.error(e);inventoryCache=[]}populateBranchSelects();renderInventory()}
function renderInventory(){const q=$("inventorySearch")?.value.toLowerCase()||"",type=$("inventoryType")?.value||"",br=$("inventoryBranch")?.value||"";let list=inventoryCache.filter(i=>`${i.name||i.itemName} ${i.supplierName||i.supplier||""}`.toLowerCase().includes(q));if(type)list=list.filter(i=>(i.type||"raw")===type);if(br)list=list.filter(i=>(i.branchId||"")===br);$("inventoryBody").innerHTML=list.map(i=>{const qty=Number(i.quantity??i.stock??0),min=Number(i.minimumStock??i.minStock??0);return `<tr><td><b>${esc(i.name||i.itemName||"—")}</b><br><small>${esc(i.sku||"")}</small></td><td>${esc(i.type||"raw")}</td><td><span class="pill ${qty<=min?"warn":"ok"}">${qty} ${esc(i.unit||"unit")}</span></td><td>${min}</td><td>${money(i.unitCost||0)}</td><td>${esc(i.supplierName||i.supplier||"—")}</td><td>${esc(branchName(i.branchId)||"Factory")}</td><td><div class="actions"><button data-edit-inv="${i.id}">Edit</button><button data-stock-in="${i.id}">Stock In</button><button data-stock-out="${i.id}">Stock Out</button></div></td></tr>`}).join("")||`<tr><td colspan="8" class="empty-cell">No inventory records.</td></tr>`;$("inventoryBody").querySelectorAll("[data-edit-inv]").forEach(b=>b.onclick=()=>openModal("inventory",inventoryCache.find(x=>x.id===b.dataset.editInv)));$("inventoryBody").querySelectorAll("[data-stock-in]").forEach(b=>b.onclick=()=>openModal("stockmove",{itemId:b.dataset.stockIn,mode:"in"}));$("inventoryBody").querySelectorAll("[data-stock-out]").forEach(b=>b.onclick=()=>openModal("stockmove",{itemId:b.dataset.stockOut,mode:"out"}))}
$("inventorySearch")?.addEventListener("input",renderInventory);$("inventoryType")?.addEventListener("change",renderInventory);$("inventoryBranch")?.addEventListener("change",renderInventory);

// PURCHASES + SUPPLIERS
async function loadPurchases(){try{purchasesCache=await safeGet("purchases",{order:"createdAt",limit:500})}catch(e){purchasesCache=[]}renderPurchases();renderPriceAlerts()}
async function loadSuppliers(){try{suppliersCache=await safeGet("suppliers",{limit:300})}catch(e){suppliersCache=[]}renderSuppliers()}
function renderPurchases(){const body=$("purchasesBody");body.innerHTML=purchasesCache.map(p=>`<tr><td>${fmtDate(p.createdAt)}</td><td>${esc(p.invoiceNo||p.id.slice(0,8))}</td><td>${esc(p.supplierName||"—")}</td><td>${esc(p.itemName||"—")}</td><td>${p.quantity||0} ${esc(p.unit||"")}</td><td>${money(p.unitCost)}</td><td><b>${money(p.totalCost||Number(p.quantity||0)*Number(p.unitCost||0))}</b></td></tr>`).join("")||`<tr><td colspan="7" class="empty-cell">No purchase history.</td></tr>`}
function renderSuppliers(){$("suppliersBody").innerHTML=suppliersCache.map(s=>`<tr><td><b>${esc(s.name)}</b><br><small>${esc(s.address||"")}</small></td><td>${esc(s.phone||"—")}</td><td>${esc(s.items||"—")}</td><td><div class="actions"><button data-edit-supplier="${s.id}">Edit</button><button data-del-supplier="${s.id}">Delete</button></div></td></tr>`).join("")||`<tr><td colspan="4" class="empty-cell">No suppliers yet.</td></tr>`;document.querySelectorAll("[data-edit-supplier]").forEach(b=>b.onclick=()=>openModal("supplier",suppliersCache.find(x=>x.id===b.dataset.editSupplier)));document.querySelectorAll("[data-del-supplier]").forEach(b=>b.onclick=()=>removeRecord("suppliers",b.dataset.delSupplier))}
function renderPriceAlerts(){const alerts=purchasesCache.filter(p=>Number(p.previousUnitCost)>0&&Number(p.unitCost)>Number(p.previousUnitCost)*1.05).slice(0,8);$("priceAlerts").innerHTML=alerts.map(p=>`<div class="alert-item"><div class="alert-icon">📈</div><div><b>${esc(p.itemName)}</b><small>${money(p.previousUnitCost)} → ${money(p.unitCost)} (${Math.round((p.unitCost/p.previousUnitCost-1)*100)}% increase)</small></div></div>`).join("")||`<div class="empty-cell">No significant price increases recorded.</div>`}

// Recalculate saved production costs whenever ingredient prices change.
async function recalculateSavedCosts(){
  try{
    const snap=await getDocs(collection(db,"productCosts"));
    for(const d of snap.docs){
      const r=d.data(); let ingredientCost=0;
      (r.ingredients||[]).forEach(i=>{
        const item=inventoryCache.find(x=>x.id===i.itemId);
        if(!item)return;
        const base=item.unit||"kg", chosen=i.unit||base; let factor=1;
        if(base==="kg"&&chosen==="g")factor=.001; if(base==="g"&&chosen==="kg")factor=1000;
        if(base==="L"&&chosen==="ml")factor=.001; if(base==="ml"&&chosen==="L")factor=1000;
        ingredientCost+=Number(i.qty||0)*factor*Number(item.unitCost||0);
      });
      const overhead=Number(r.electricity||0)+Number(r.labour||0), total=ingredientCost+overhead, unitCost=total/Math.max(1,Number(r.yield||1));
      await updateDoc(doc(db,"productCosts",d.id),{ingredientCost,overhead,totalCost:total,unitCost,updatedAt:serverTimestamp()});
    }
  }catch(e){console.warn("Saved cost recalculation failed",e)}
}

// COST CALCULATOR
async function loadRecipes(){try{recipesCache=await safeGet("productCosts",{order:"updatedAt",limit:300})}catch(e){recipesCache=[]}renderRecipes()}
async function loadCostPanel(){await loadInventory();await loadRecipes();if(!$('recipeRows').children.length)addRecipeRow()}
function addRecipeRow(data={}){const wrap=$("recipeRows"),row=document.createElement("div");row.className="recipe-row";row.innerHTML=`<select class="recipe-item"><option value="">Ingredient…</option>${inventoryCache.filter(i=>(i.type||"raw")==="raw").map(i=>`<option value="${esc(i.id)}" ${i.id===data.itemId?"selected":""}>${esc(i.name||i.itemName)}</option>`).join("")}</select><input class="recipe-qty" type="number" min="0" step="0.001" value="${Number(data.qty||0)}" placeholder="Qty"><select class="recipe-unit"><option value="kg">kg</option><option value="g">g</option><option value="L">L</option><option value="ml">ml</option><option value="pcs">pcs</option></select><button type="button">×</button>`;row.querySelector("button").onclick=()=>row.remove();wrap.appendChild(row)}
$("addRecipeRow")?.addEventListener("click",()=>addRecipeRow());
$("calculateCost")?.addEventListener("click",async()=>{const product=$("costProduct").value.trim();const yieldQty=Number($("costYield").value||1);if(!product||yieldQty<=0)return toast("Enter a product and yield");const ingredients=[];let ingredientTotal=0;for(const row of document.querySelectorAll(".recipe-row")){const item=inventoryCache.find(i=>i.id===row.querySelector(".recipe-item").value),qty=Number(row.querySelector(".recipe-qty").value||0);if(!item||qty<=0)continue;const baseUnit=item.unit||"kg";let factor=1;const chosen=row.querySelector(".recipe-unit").value;if(baseUnit==="kg"&&chosen==="g")factor=.001;if(baseUnit==="g"&&chosen==="kg")factor=1000;if(baseUnit==="L"&&chosen==="ml")factor=.001;if(baseUnit==="ml"&&chosen==="L")factor=1000;const cost=qty*factor*Number(item.unitCost||0);ingredientTotal+=cost;ingredients.push({itemId:item.id,name:item.name||item.itemName,qty,unit:chosen,unitCost:Number(item.unitCost||0),lineCost:cost})}const overhead=Number($("costElectricity").value||0)+Number($("costLabour").value||0),total=ingredientTotal+overhead,unitCost=total/yieldQty;$("costTotal").textContent=money(unitCost)+" / unit";$("costBreakdown").textContent=`Ingredients ${money(ingredientTotal)} + overhead ${money(overhead)} = ${money(total)} total`;$("costBody").innerHTML=ingredients.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty} ${esc(i.unit)}</td><td>${money(i.unitCost)}</td><td>${money(i.lineCost)}</td></tr>`).join("")||`<tr><td colspan="4" class="empty-cell">No ingredients selected.</td></tr>`;if(canEdit("cost")){await addDoc(collection(db,"productCosts"),{productName:product,yield:yieldQty,ingredients,ingredientCost:ingredientTotal,electricity:Number($("costElectricity").value||0),labour:Number($("costLabour").value||0),overhead,totalCost:total,unitCost,updatedAt:serverTimestamp(),updatedBy:currentUser.uid});await logActivity("Product cost calculated/saved","productCosts",product,`Unit cost ${money(unitCost)}`);await loadRecipes();toast("Product cost saved")}});
function renderRecipes(){$("recipesBody").innerHTML=recipesCache.map(r=>`<tr><td><b>${esc(r.productName)}</b></td><td>${r.yield||1}</td><td>${money(r.ingredientCost)}</td><td>${money(r.overhead)}</td><td><b>${money(r.unitCost)}</b></td><td>${fmtDate(r.updatedAt)}</td></tr>`).join("")||`<tr><td colspan="6" class="empty-cell">No saved recipes.</td></tr>`}

// BRANCHES
async function loadBranches(){try{branchesCache=await safeGet("branches",{limit:100})}catch(e){branchesCache=[]}populateBranchSelects();renderBranches()}
function branchName(id){return branchesCache.find(b=>b.id===id)?.name||branchesCache.find(b=>b.id===id)?.branchName||id||""}
function populateBranchSelects(){const opts=branchesCache.map(b=>`<option value="${esc(b.id)}">${esc(b.name||b.branchName)}</option>`).join("");["inventoryBranch","formBranch","deliveryBranch","employeeBranch","attendanceBranch","orderBranch"].forEach(id=>{const el=$(id);if(!el)return;const current=el.value;el.innerHTML=`<option value="">${id==="inventoryBranch"?"All branches":"Select branch…"}</option>${opts}`;if(current)el.value=current;if(currentProfile?.branchId&&currentRole==="branch_manager")el.value=currentProfile.branchId})}
function renderBranches(){$("branchesBody").innerHTML=branchesCache.map(b=>`<tr><td><b>${esc(b.name||b.branchName)}</b></td><td>${esc(b.address||"—")}</td><td>${esc(b.phone||"—")}</td><td>${esc(b.managerName||"—")}</td><td><div class="actions">${(currentRole==="admin"||currentRole==="manager")?`<button data-edit-branch="${b.id}">Edit</button><button data-del-branch="${b.id}">Delete</button>`:"View only"}</div></td></tr>`).join("")||`<tr><td colspan="5" class="empty-cell">No branches.</td></tr>`;$("branchCards").innerHTML=branchesCache.map(b=>`<div class="card"><span class="eyebrow">BRANCH</span><h3>${esc(b.name||b.branchName)}</h3><p class="help">${esc(b.address||"")}</p><div class="stat-card"><small>Manager</small><b style="font-size:15px">${esc(b.managerName||"—")}</b></div></div>`).join("");document.querySelectorAll("[data-edit-branch]").forEach(b=>b.onclick=()=>openModal("branch",branchesCache.find(x=>x.id===b.dataset.editBranch)));document.querySelectorAll("[data-del-branch]").forEach(b=>b.onclick=()=>removeRecord("branches",b.dataset.delBranch))}

// DELIVERIES
async function loadDeliveries(){try{deliveriesCache=await safeGet("shipments",{order:"createdAt",limit:300})}catch(e){deliveriesCache=[]}renderDeliveries()}
function renderDeliveries(){const f=$("deliveryStatusFilter")?.value||"";const list=deliveriesCache.filter(d=>!f||(d.status||"pending")===f);$("deliveriesBody").innerHTML=list.map(d=>`<tr><td>${fmtDate(d.createdAt)}</td><td>${esc(d.products||d.items||"—")}<br><small>${esc(d.quantity||"")}</small></td><td>${esc(d.branchName||branchName(d.branchId)||"—")}</td><td>${esc(d.driverName||d.deliveryPerson||"—")}</td><td>${fmtDate(d.dispatchTime)}</td><td>${fmtDate(d.receivedTime)}</td><td><span class="pill ${d.status==="received"||d.status==="delivered"?"ok":d.status==="pending"?"warn":"info"}">${esc(d.status||"pending")}</span></td><td><div class="actions"><button data-edit-delivery="${d.id}">Edit</button></div></td></tr>`).join("")||`<tr><td colspan="8" class="empty-cell">No deliveries.</td></tr>`;document.querySelectorAll("[data-edit-delivery]").forEach(b=>b.onclick=()=>openModal("delivery",deliveriesCache.find(x=>x.id===b.dataset.editDelivery)))}
$("deliveryStatusFilter")?.addEventListener("change",renderDeliveries);

// STAFF + ATTENDANCE
async function loadEmployees(){try{employeesCache=await safeGet("employees",{limit:300})}catch(e){employeesCache=[]}renderEmployees()}
async function loadAttendance(){try{attendanceCache=await safeGet("attendance",{order:"createdAt",limit:500})}catch(e){attendanceCache=[]}renderAttendance()}
async function loadStaff(){await Promise.all([loadEmployees(),loadAttendance()])}
function renderEmployees(){$("employeesBody").innerHTML=employeesCache.map(e=>`<tr><td><b>${esc(e.name)}</b></td><td>${esc(ROLE_LABELS[e.role]||e.role||"Staff")}</td><td>${esc(branchName(e.branchId)||"—")}</td><td>${money(e.salary||0)}</td><td>${esc(e.phone||"—")}</td><td><div class="actions"><button data-edit-employee="${e.id}">Edit</button></div></td></tr>`).join("")||`<tr><td colspan="6" class="empty-cell">No staff profiles.</td></tr>`;document.querySelectorAll("[data-edit-employee]").forEach(b=>b.onclick=()=>openModal("employee",employeesCache.find(x=>x.id===b.dataset.editEmployee)))}
function renderAttendance(){const today=dateKey(new Date());const list=attendanceCache.filter(a=>dateKey(a.date||a.createdAt)===today).slice(0,50);$("attendanceBody").innerHTML=list.map(a=>`<tr><td>${esc(a.employeeName||a.name||a.employeeId||"—")}</td><td><span class="pill ${a.status==="present"?"ok":a.status==="absent"?"danger":"warn"}">${esc(a.status||"present")}</span></td><td>${fmtDate(a.time||a.createdAt)}</td><td>${a.proofUrl?`<a href="${esc(a.proofUrl)}" target="_blank" rel="noopener">View</a>`:"—"}</td></tr>`).join("")||`<tr><td colspan="4" class="empty-cell">No attendance records today.</td></tr>`}

// ORDERS
async function loadOrders(){try{ordersCache=await safeGet("orders",{order:"createdAt",limit:500})}catch(e){ordersCache=[]}renderOrders()}
function fulfillmentCell(o){return o.fulfillment==="pickup"?`🏪 ${esc(o.customer?.pickupBranch||branchName(o.branchId)||"Pickup")}`:`🚚 ${esc(o.branchName||branchName(o.branchId)||o.customer?.area||"Delivery")}`}
function orderRow(o){const status=o.orderStatus||"pending";const edit=hasPerm("orders")||hasPerm("inventory")||hasPerm("deliveries")||["manager","admin","staff","branch_manager"].includes(currentRole);return `<tr><td><span class="mono">${esc(o.id.slice(0,8))}</span><br><small>${fmtDate(o.createdAt)}</small></td><td>${esc(o.customer?.name||o.customerName||"—")}<br><small>${esc(o.customer?.phone||o.phone||"")}</small></td><td>${(o.items||[]).map(i=>`${esc(i.name)} ×${i.qty}`).join(", ")||esc(o.itemsText||"—")}</td><td><b>${money(o.total)}</b><br><small>${esc(o.paymentMethod||"")}</small></td><td>${fulfillmentCell(o)}</td><td>${edit?`<select class="status-select" data-order-id="${o.id}">${ORDER_STEPS.map(s=>`<option value="${s}" ${s===status?"selected":""}>${s.replaceAll("_"," ")}</option>`).join("")}</select>`:`<span class="pill info">${esc(status)}</span>`}</td><td><div class="actions">${status==="pending"&&edit?`<button data-accept-order="${o.id}">Accept</button>`:""}${o.customer?.phone?`<a href="tel:${esc(o.customer.phone)}">Call</a>`:""}</div></td></tr>`}
function renderOrders(){const q=$("orderSearch")?.value.trim().toLowerCase()||"",f=$("orderStatusFilter")?.value||"";let list=ordersCache.filter(o=>`${o.id} ${o.customer?.name||""} ${o.customer?.phone||""}`.toLowerCase().includes(q));if(f)list=list.filter(o=>(o.orderStatus||"pending")===f);$("ordersBody").innerHTML=list.map(orderRow).join("")||`<tr><td colspan="7" class="empty-cell">No orders found.</td></tr>`;bindOrderControls($("ordersBody"));renderRecentOrders()}
function bindOrderControls(body){body?.querySelectorAll(".status-select").forEach(s=>s.onchange=async()=>{try{await updateDoc(doc(db,"orders",s.dataset.orderId),{orderStatus:s.value,updatedAt:serverTimestamp()});const o=ordersCache.find(x=>x.id===s.dataset.orderId);if(o)o.orderStatus=s.value;await logActivity("Order status changed","orders",s.dataset.orderId,s.value);toast("Order updated");renderOrders()}catch(e){console.error(e);toast("Could not update order")}});body?.querySelectorAll("[data-accept-order]").forEach(b=>b.onclick=async()=>{try{await updateDoc(doc(db,"orders",b.dataset.acceptOrder),{orderStatus:"confirmed",updatedAt:serverTimestamp()});const o=ordersCache.find(x=>x.id===b.dataset.acceptOrder);if(o)o.orderStatus="confirmed";await logActivity("Order accepted","orders",b.dataset.acceptOrder);renderOrders()}catch(e){toast("Could not accept order")}})}
$("orderSearch")?.addEventListener("input",renderOrders);$("orderStatusFilter")?.addEventListener("change",renderOrders);

// REPORTS
function rangePreset(v){const end=new Date();end.setHours(23,59,59,999);const start=new Date();if(v==="today")start.setHours(0,0,0,0);else if(v==="week"){const day=start.getDay();start.setDate(start.getDate()-day);start.setHours(0,0,0,0)}else{start.setDate(1);start.setHours(0,0,0,0)}return{start,end}}
$("reportPreset")?.addEventListener("change",()=>{const c=$("reportPreset").value==="custom";$("reportStart").classList.toggle("field-hidden",!c);$("reportEnd").classList.toggle("field-hidden",!c)});
function currentRange(){if($("reportPreset").value==="custom")return{start:new Date($("reportStart").value+"T00:00:00"),end:new Date($("reportEnd").value+"T23:59:59")};return rangePreset($("reportPreset").value)}
async function generateReport(){if(!hasPerm("reports"))return;try{if(!reportsOrdersCache.length)reportsOrdersCache=await safeGet("orders",{order:"createdAt",limit:1000});if(!expensesCache.length)expensesCache=await safeGet("expenses",{order:"createdAt",limit:1000});const {start,end}=currentRange();const valid=reportsOrdersCache.filter(o=>o.orderStatus!=="cancelled"&&(()=>{const d=o.createdAt?.toDate?o.createdAt.toDate():new Date(o.createdAt);return d>=start&&d<=end})());const revenue=valid.reduce((a,o)=>a+Number(o.total||0),0),ex=expensesCache.filter(e=>{const d=e.createdAt?.toDate?e.createdAt.toDate():new Date(e.createdAt);return d>=start&&d<=end}).reduce((a,e)=>a+Number(e.amount||0),0);const products=new Map(),branches=new Map(),days=new Map();valid.forEach(o=>{const day=dateKey(o.createdAt);days.set(day,(days.get(day)||0)+Number(o.total||0));const bk=o.branchName||branchName(o.branchId)||o.customer?.pickupBranch||"Unassigned";branches.set(bk,(branches.get(bk)||{count:0,revenue:0}));branches.get(bk).count++;branches.get(bk).revenue+=Number(o.total||0);(o.items||[]).forEach(i=>{const p=products.get(i.name)||{qty:0,revenue:0};p.qty+=Number(i.qty||0);p.revenue+=Number(i.qty||0)*Number(i.price||0);products.set(i.name,p)})});const report={orders:valid,revenue,expenses:ex,profit:revenue-ex,products:[...products.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.revenue-a.revenue),branches:[...branches.entries()].map(([name,v])=>({name,...v})),days:[...days.entries()].sort()};window.lastReport=report;$("repRevenue").textContent=money(revenue);$("repOrders").textContent=valid.length;$("repExpenses").textContent=money(ex);$("repProfit").textContent=money(report.profit);$("repProfit").className=report.profit<0?"kpi-negative":"kpi-positive";const max=Math.max(1,...report.days.map(x=>x[1]));$("repChart").innerHTML=report.days.map(([d,v])=>`<div class="bar-col"><b>${money(v)}</b><div class="bar" style="height:${Math.max(4,Math.round(v/max*100))}%"></div><small>${new Date(d+"T00:00:00").toLocaleDateString("en-BD",{day:"2-digit",month:"short"})}</small></div>`).join("")||`<div class="empty-cell">No sales in this range.</div>`;$("repProductsBody").innerHTML=report.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.qty}</td><td>${money(p.revenue)}</td></tr>`).join("")||`<tr><td colspan="3" class="empty-cell">No data.</td></tr>`;$("repBranchesBody").innerHTML=report.branches.map(b=>`<tr><td>${esc(b.name)}</td><td>${b.count}</td><td>${money(b.revenue)}</td></tr>`).join("")||`<tr><td colspan="3" class="empty-cell">No data.</td></tr>`}catch(e){console.error(e);toast("Could not generate report")}}
$("reportGenerate")?.addEventListener("click",generateReport);
$("reportExportExcel")?.addEventListener("click",()=>{const r=window.lastReport;if(!r||!window.XLSX)return toast("Generate a report first");const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Metric:"Revenue",Value:r.revenue},{Metric:"Orders",Value:r.orders.length},{Metric:"Expenses",Value:r.expenses},{Metric:"Profit/Loss",Value:r.profit}]),"Summary");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.products.map(p=>({Product:p.name,Qty:p.qty,Revenue:p.revenue}))),"Products");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.branches.map(b=>({Branch:b.name,Orders:b.count,Revenue:b.revenue}))),"Branches");XLSX.writeFile(wb,`bagdad-management-report-${dateKey(new Date())}.xlsx`)});
$("reportExportPdf")?.addEventListener("click",()=>{const r=window.lastReport;if(!r||!window.jspdf)return toast("Generate a report first");const {jsPDF}=window.jspdf,pdf=new jsPDF();pdf.text("Bagdad Bread Factory & Sweets — Management Report",14,16);pdf.setFontSize(9);pdf.text(`Generated ${new Date().toLocaleString("en-BD")}`,14,23);pdf.autoTable({startY:30,head:[["Metric","Value"]],body:[["Revenue",money(r.revenue)],["Orders",String(r.orders.length)],["Expenses",money(r.expenses)],["Profit/Loss",money(r.profit)]]});pdf.autoTable({startY:pdf.lastAutoTable.finalY+8,head:[["Product","Qty","Revenue"]],body:r.products.map(p=>[p.name,p.qty,money(p.revenue)])});pdf.save(`bagdad-management-report-${dateKey(new Date())}.pdf`)});

// NOTIFICATIONS
async function loadNotifications(){await Promise.allSettled([loadInventory(),loadPurchases(),loadDeliveries(),loadAttendance(),loadOrders(),loadEmployees()]);renderAlerts()}
$("refreshAlerts")?.addEventListener("click",loadNotifications);

// USERS
async function loadUsers(){if(!hasPerm("users"))return;try{const list=await safeGet("users",{limit:500});const roles=["customer","delivery","staff","manager","branch_manager","factory_staff","attendance_staff","admin"];$("usersBody").innerHTML=list.map(u=>`<tr><td><b>${esc(u.name||"—")}</b></td><td>${esc(u.email||"—")}<br><small class="mono">${esc(u.id)}</small></td><td>${esc(u.phoneNumber||u.phone||"—")}</td><td><select class="status-select" data-user-role="${u.id}" ${u.id===currentUser.uid?"disabled":""}>${roles.map(r=>`<option value="${r}" ${r===(u.role||"")?"selected":""}>${ROLE_LABELS[r]||r}</option>`).join("")}</select></td><td><select class="status-select" data-user-branch="${u.id}"><option value="">No branch</option>${branchesCache.map(b=>`<option value="${b.id}" ${u.branchId===b.id?"selected":""}>${esc(b.name)}</option>`).join("")}</select></td><td>${u.id===currentUser.uid?"Current user":""}</td></tr>`).join("")||`<tr><td colspan="6" class="empty-cell">No users.</td></tr>`;document.querySelectorAll("[data-user-role]").forEach(s=>s.onchange=async()=>{try{await updateDoc(doc(db,"users",s.dataset.userRole),{role:s.value});await logActivity("User role changed","users",s.dataset.userRole,s.value);toast("Role updated")}catch(e){toast("Role update failed")}});document.querySelectorAll("[data-user-branch]").forEach(s=>s.onchange=async()=>{try{await updateDoc(doc(db,"users",s.dataset.userBranch),{branchId:s.value||null});await logActivity("User branch changed","users",s.dataset.userBranch,s.value);toast("Branch updated")}catch(e){toast("Branch update failed")}})}catch(e){console.error(e);$("usersBody").innerHTML=`<tr><td colspan="6" class="empty-cell">Could not load users.</td></tr>`}}

// ACTIVITY LOG
async function loadActivity(){if(!hasPerm("activity"))return;try{let q=query(collection(db,"activityLogs"),orderBy("createdAt","desc"),limit(300));if(currentRole==="branch_manager"&&branchId)q=query(collection(db,"activityLogs"),where("branchId","==",branchId),orderBy("createdAt","desc"),limit(300));const s=await getDocs(q);$("activityBody").innerHTML=s.docs.map(d=>{const x=d.data();return `<tr><td>${fmtDate(x.createdAt)}</td><td>${esc(x.userName||x.userId||"—")}</td><td>${esc(ROLE_LABELS[x.role]||x.role||"—")}</td><td><b>${esc(x.action)}</b></td><td>${esc(x.collection)}</td><td class="mono">${esc(x.recordId)}</td><td>${esc(x.details||"")}</td></tr>`}).join("")||`<tr><td colspan="7" class="empty-cell">No activity recorded.</td></tr>`}catch(e){console.error(e);$("activityBody").innerHTML=`<tr><td colspan="7" class="empty-cell">Could not load activity logs.</td></tr>`}}
$("refreshActivity")?.addEventListener("click",loadActivity);

// EXPENSES helper
async function loadExpenses(){try{expensesCache=await safeGet("expenses",{order:"createdAt",limit:500})}catch(e){expensesCache=[]}}

// MODAL FOR CRUD
const backdrop=$("modalBackdrop"),modalTitle=$("modalTitle"),modalBody=$("modalBody");
function closeModal(){backdrop.classList.remove("open");modalBody.innerHTML=""}$("modalClose")?.addEventListener("click",closeModal);backdrop?.addEventListener("click",e=>{if(e.target===backdrop)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const forms={
 inventory:{title:"Stock Item",collection:"inventory",perm:"inventory",fields:[['name','Item / Product','text',true],['type','Type','select',true,['raw','finished']],['quantity','Opening stock','number',true],['unit','Unit','select',true,['kg','g','L','ml','pcs','box','unit']],['minimumStock','Minimum stock','number',true],['unitCost','Current unit cost (৳)','number',true],['supplierName','Supplier','text'],['branchId','Branch','branch'],['sku','SKU','text']]},
 supplier:{title:"Supplier",collection:"suppliers",perm:"purchases",fields:[['name','Supplier name','text',true],['phone','Phone','text'],['email','Email','email'],['address','Address','text'],['items','Supplies / items','text']]},
 branch:{title:"Branch",collection:"branches",perm:"branches",fields:[['name','Branch name','text',true],['address','Address','text',true],['phone','Phone','text'],['managerName','Manager name','text'],['managerUid','Manager user UID','text']]},
 purchase:{title:"Purchase Invoice",collection:"purchases",perm:"purchases",fields:[['invoiceNo','Invoice number','text'],['supplierName','Supplier','text',true],['itemName','Ingredient / item','text',true],['quantity','Quantity','number',true],['unit','Unit','text',true],['unitCost','Unit purchase price (৳)','number',true],['branchId','Received at branch','branch'],['notes','Notes','text']]},
 transfer:{title:"Factory → Branch Stock Transfer",collection:"stockTransfers",perm:"inventory",fields:[['itemName','Product / item','text',true],['quantity','Quantity','number',true],['unit','Unit','text',true],['branchId','Destination branch','branch',true],['driverName','Driver / delivery person','text'],['notes','Notes','text']]},
 stockmove:{title:"Stock Movement",collection:"inventory",fields:[['quantity','Quantity','number',true],['notes','Reason / note','text']]},
 delivery:{title:"Delivery Dispatch",collection:"shipments",perm:"deliveries",fields:[['products','Products / quantities','text',true],['branchId','Destination branch','branch',true],['driverName','Driver / delivery person','text',true],['dispatchTime','Dispatch time','datetime-local'],['receivedTime','Received time','datetime-local'],['status','Status','select',true,['pending','dispatched','received','delivered']],['notes','Notes','text']]},
 employee:{title:"Staff Profile",collection:"employees",perm:"staff",fields:[['name','Full name','text',true],['role','Role','select',true,['staff','factory_staff','attendance_staff','delivery','manager','branch_manager']],['branchId','Assigned branch','branch'],['phone','Phone','text'],['salary','Salary (৳)','number'],['workingHours','Working hours','text'],['leaveBalance','Leave balance','number'],['photoUrl','Photo URL','url']]},
 attendance:{title:"Attendance",collection:"attendance",perm:"staff",fields:[['employeeId','Staff','employee',true],['status','Status','select',true,['present','absent','late','leave']],['date','Date','date',true],['time','Time','datetime-local'],['proofUrl','Photo / proof URL','url'],['notes','Notes','text']]},
 order:{title:"Manual / WhatsApp Order",collection:"orders",perm:"orders",fields:[['customerName','Customer name','text',true],['phone','Customer phone','text'],['itemsText','Items and quantities','text',true],['total','Order total (৳)','number',true],['branchId','Branch','branch'],['fulfillment','Fulfillment','select',true,['delivery','pickup']],['paymentMethod','Payment method','text'],['orderStatus','Status','select',true,['pending','confirmed','preparing','ready_for_pickup','out_for_delivery','delivered','cancelled']]]},
 expense:{title:"Expense",collection:"expenses",perm:"reports",fields:[['category','Category','text',true],['description','Description','text',true],['amount','Amount (৳)','number',true],['branchId','Branch','branch'],['date','Date','date',true]]}
};
function fieldHtml([key,label,type,required,options],value){let val=value??"";if(type==="branch"){return `<div class="form-field"><label>${esc(label)}</label><select name="${key}" ${required?"required":""}><option value="">Select branch…</option>${branchesCache.map(b=>`<option value="${esc(b.id)}" ${String(val)===String(b.id)?"selected":""}>${esc(b.name||b.branchName)}</option>`).join("")}</select></div>`}if(type==="employee"){return `<div class="form-field"><label>${esc(label)}</label><select name="${key}" required><option value="">Select staff…</option>${employeesCache.map(e=>`<option value="${esc(e.id)}" ${String(val)===String(e.id)?"selected":""}>${esc(e.name)}</option>`).join("")}</select></div>`}if(type==="select")return `<div class="form-field"><label>${esc(label)}</label><select name="${key}" ${required?"required":""}>${options.map(o=>`<option value="${esc(o)}" ${String(val)===String(o)?"selected":""}>${esc(o.replaceAll("_"," "))}</option>`).join("")}</select></div>`;return `<div class="form-field"><label>${esc(label)}</label><input name="${key}" type="${type}" value="${esc(val)}" ${required?"required":""} ${type==="number"?"step=\"0.01\" min=\"0\"":""}></div>`}
function openModal(type,data={}){if(type==="stockmove"){const item=inventoryCache.find(i=>i.id===data.itemId);modalTitle.textContent=data.mode==="in"?"Stock In":"Stock Out";modalBody.innerHTML=`<form id="dynamicForm"><p class="help" style="font-size:10px;margin-bottom:12px">${esc(item?.name||"Item")}: current ${item?.quantity??item?.stock??0} ${esc(item?.unit||"")}</p><div class="form-grid">${fieldHtml(forms.stockmove.fields[0],"")}${fieldHtml(forms.stockmove.fields[1],"")}</div><div class="form-actions"><button class="btn outline" type="button" id="formCancel">Cancel</button><button class="btn primary">Save</button></div></form>`;bindDynamic(()=>stockMove(data));backdrop.classList.add("open");return}if(type==="expense"){}const f=forms[type];if(!f)return;modalTitle.textContent=(data?.id?"Edit ":"Add ")+f.title;modalBody.innerHTML=`<form id="dynamicForm"><div class="form-grid">${f.fields.map(x=>fieldHtml(x,data?.[x[0]])).join("")}</div>${type==="purchase"?`<p class="help" style="font-size:9px;margin-top:8px">Saving a purchase also updates the ingredient's inventory cost and keeps the previous price for price-history alerts.</p>`:""}<div class="form-actions"><button class="btn outline" type="button" id="formCancel">Cancel</button><button class="btn primary">Save</button></div></form>`;bindDynamic(()=>saveForm(type,data));backdrop.classList.add("open")}
function bindDynamic(fn){$("formCancel").onclick=closeModal;$("dynamicForm").onsubmit=async e=>{e.preventDefault();await fn(new FormData(e.target))}}
async function saveForm(type,data,fd){const f=forms[type];if(f.perm&&!canEdit(f.perm))return toast("You do not have permission");const values={};for(const [k] of f.fields){let v=fd.get(k);if(["quantity","minimumStock","unitCost","salary","leaveBalance","total","amount"].includes(k))v=v===""?0:Number(v);if(["date","time","dispatchTime","receivedTime"].includes(k)&&v)v=new Date(v);values[k]=v}if(type==="order"){values.customer={name:values.customerName||"",phone:values.phone||""};values.items=[];values.createdAt=serverTimestamp()}try{if(type==="purchase"){const old=inventoryCache.find(i=>(i.name||i.itemName||"").toLowerCase()===String(values.itemName).toLowerCase());values.previousUnitCost=Number(old?.unitCost||0);values.totalCost=Number(values.quantity||0)*Number(values.unitCost||0);values.createdAt=serverTimestamp();await addDoc(collection(db,"purchases"),values);if(old)await updateDoc(doc(db,"inventory",old.id),{unitCost:Number(values.unitCost||0),supplierName:values.supplierName,quantity:Number(old.quantity??old.stock??0)+Number(values.quantity||0),updatedAt:serverTimestamp()});else await addDoc(collection(db,"inventory"),{name:values.itemName,type:"raw",quantity:Number(values.quantity||0),unit:values.unit,minimumStock:0,unitCost:Number(values.unitCost||0),supplierName:values.supplierName,branchId:values.branchId||null,createdAt:serverTimestamp()});await logActivity("Purchase recorded","purchases",values.invoiceNo||values.itemName,`${values.itemName} ${money(values.unitCost)}`);await loadInventory();await recalculateSavedCosts();await loadRecipes();await loadPurchases();toast("Purchase saved and stock updated");closeModal();return}
if(type==="transfer"){
  values.createdAt=serverTimestamp();values.from="factory";
  const qty=Number(values.quantity||0), source=inventoryCache.find(i=>(i.name||i.itemName||"").toLowerCase()===String(values.itemName).toLowerCase() && (!i.branchId || i.branchId==="factory"));
  if(!source)return toast("Factory stock item not found");
  const sourceQty=Number(source.quantity??source.stock??0);if(qty<=0||sourceQty<qty)return toast("Not enough factory stock");
  const target=inventoryCache.find(i=>(i.name||i.itemName||"").toLowerCase()===String(values.itemName).toLowerCase()&&i.branchId===values.branchId);
  await updateDoc(doc(db,"inventory",source.id),{quantity:sourceQty-qty,updatedAt:serverTimestamp()});
  if(target)await updateDoc(doc(db,"inventory",target.id),{quantity:Number(target.quantity??target.stock??0)+qty,unitCost:Number(source.unitCost||target.unitCost||0),updatedAt:serverTimestamp()});
  else await addDoc(collection(db,"inventory"),{name:values.itemName,type:"finished",quantity:qty,unit:values.unit,minimumStock:0,unitCost:Number(source.unitCost||0),supplierName:"",branchId:values.branchId,createdAt:serverTimestamp()});
  await addDoc(collection(db,"stockTransfers"),values);await logActivity("Stock transferred","stockTransfers",values.itemName,`Factory → ${branchName(values.branchId)} / ${values.quantity}`);await loadInventory();toast("Stock transferred and branch stock updated");closeModal();return
}
if(type==="delivery"){values.branchName=branchName(values.branchId);values.createdAt=serverTimestamp();await addDoc(collection(db,"shipments"),values);await logActivity("Delivery dispatch created","shipments",values.branchId,`${values.products} → ${values.branchName}`);await loadDeliveries();toast("Delivery saved");closeModal();return}
if(type==="employee"){values.createdAt=serverTimestamp();if(data.id)await updateDoc(doc(db,"employees",data.id),values);else await addDoc(collection(db,"employees"),values);await logActivity(data.id?"Staff profile updated":"Staff profile created","employees",data.id||values.name);await loadEmployees();toast("Staff profile saved");closeModal();return}
if(type==="attendance"){values.employeeName=employeesCache.find(e=>e.id===values.employeeId)?.name||"";values.createdAt=serverTimestamp();if(!values.date)values.date=new Date();await addDoc(collection(db,"attendance"),values);await logActivity("Attendance submitted","attendance",values.employeeId,values.status);await loadAttendance();toast("Attendance saved");closeModal();return}
if(type==="order"){const items=String(values.itemsText||"").split(",").map(x=>x.trim()).filter(Boolean).map(x=>{const m=x.match(/^(.*?)(?:\s*[x×]\s*(\d+(?:\.\d+)?))?$/i);return{name:(m?.[1]||x).trim(),qty:Number(m?.[2]||1),price:0}});values.items=items;values.branchName=branchName(values.branchId);delete values.customerName;delete values.phone;delete values.itemsText;values.userId=currentUser.uid;const orderRef=await addDoc(collection(db,"orders"),values);await logActivity("Manual order created","orders",orderRef.id,`WhatsApp/manual order ${money(values.total)}`);await loadOrders();toast("Order added");closeModal();return}
values.updatedAt=serverTimestamp();if(data.id)await updateDoc(doc(db,f.collection,data.id),values);else{values.createdAt=serverTimestamp();await addDoc(collection(db,f.collection),values)}await logActivity(data.id?`${f.title} updated`:`${f.title} created`,f.collection,data.id||values.name||values.id||"new","");if(type==="inventory")await loadInventory();if(type==="supplier")await loadSuppliers();if(type==="branch")await loadBranches();if(type==="expense")await loadExpenses();toast(`${f.title} saved`);closeModal()}catch(e){console.error(e);toast(`Could not save ${f.title}`)}}
async function stockMove(data,fd){const item=inventoryCache.find(i=>i.id===data.itemId);if(!item)return;const qty=Number(fd.get("quantity")||0);if(qty<=0)return toast("Enter a valid quantity");const current=Number(item.quantity??item.stock??0),next=data.mode==="in"?current+qty:current-qty;if(next<0)return toast("Stock cannot go below zero");try{await updateDoc(doc(db,"inventory",item.id),{quantity:next,updatedAt:serverTimestamp()});await addDoc(collection(db,"stockMovements"),{itemId:item.id,itemName:item.name||item.itemName,mode:data.mode,quantity:qty,before:current,after:next,notes:fd.get("notes")||"",createdAt:serverTimestamp(),userId:currentUser.uid,branchId:item.branchId||null});await logActivity(data.mode==="in"?"Stock in":"Stock out","inventory",item.id,`${current} → ${next}`);await loadInventory();toast("Stock updated");closeModal()}catch(e){console.error(e);toast("Stock update failed")}}

async function removeRecord(collectionName,id){if(currentRole!=="admin"&&!(collectionName==="suppliers"&&currentRole==="manager"))return toast("Admin permission required");if(!confirm("Delete this record?"))return;try{await deleteDoc(doc(db,collectionName,id));await logActivity("Record deleted",collectionName,id);if(collectionName==="branches")await loadBranches();if(collectionName==="suppliers")await loadSuppliers();toast("Deleted")}catch(e){console.error(e);toast("Delete failed")}}

document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.open==="inventory"?"inventory":b.dataset.open)));
// Add Expense quick entry from Reports if needed from browser console or future button.

// Keep the main data views in sync after modal saves.
window.addEventListener("focus",()=>{if(currentUser&&$("appShell")&&!$("appShell").classList.contains("hidden"))loadDashboard()});
